BeBoRE/ei-noah-bot

.dockerignore, .github/workflows/docker-publish.yml, Dockerfile, ormconfig.json, src/EiNoah.ts, src/Router.ts, src/data.ts, src/entity/Category.ts, src/entity/GuildUser.ts, src/entity/TempChannel.ts, src/index.ts, src/routes/Counter.ts, src/routes/LobbyRouter.ts
Lobby systeem is bijna af er hoeven nog maar een paar features aan toegevoegd worden. Zoals ownership overgeven aan iemand anders en een help commando. Maar volgens mij is het goed genoeg om het uit te proberen.
=> Lobby Systeem

src/EiNoah.ts, src/Router.ts, src/data.ts, src/routes/LobbyRouter.ts
Fixed: Error wanneer een commando naar Ei Noah wordt gestuurd in een kanaal die niet in een category zit
Fixed: Bug waardoor Ei Noah oneindig lang bleef typen
Fixed: Iemand adden in een nospeak lobby bleven mensen gemute
Added: Verschillende icoontjes voor normale en nospeak lobbies
Changed: Wat grammatica veranderd
=> Lobby Fixes

src/routes/LobbyRouter.ts
Added: Ownership is now transferred when original owner left
=> Lobby Ownership Transfer

.github/workflows/linting.yml, ormconfig.json, src/EiNoah.ts, src/Router.ts, src/entity/Guild.ts, src/entity/GuildUser.ts, src/entity/User.ts, src/routes/LobbyRouter.ts
Toegevoegd: Je kan nu de type van je lobby veranderen met `ei lobby type [nospeak/ nojoin]`
Toegevoegd: [ADMIN] Bitrates voor de lobbies kunnen nu veranderd worden met `ei lobby bitrate <8,000-128,000>`
Fixed: Een niet toegestaande user kon lobby eigenaar worden als de huidige eigenaar uit de lobby was gegaan
=> Lobby Type Veranderen CHANGE DRIVE VOLUME

src/Router.ts, src/index.ts, src/routes/LobbyRouter.ts
```markdown
*Toevoeging*: Public lobbies
> Iedereen kan een public lobby joinen 
Maak een public lobby aan met `ei lobby create -public` 
of verander hem later naar een public lobby met `ei lobby set public`
*Verandering*: Lobby Naamgeving
>`nospeak` => `mute`
`nojoin`     => `private`
*Verandering*: `ei noah` is nu ook een prefix voor de bot
> Dat wil zeggen dat, bijvoorbeeld, `ei noah lobby create` hetzelfde doet als `ei lobby create`
```
=> Public Lobbies

.github/workflows/docker-publish.yml, src/routes/LobbyRouter.ts
Fixed: Wanneer de owner van de lobby de lobby uitgaat, kan iedereen in de lobby owner worden, niet alleen de mensen die toegestaan zijn (want in een public lobby is iedereen toegestaan)
Fixed: Je kan geen mensen meer removen uit een public lobby
Fixed: Changelog wordt nu volledig hier neergezet
=> Public Lobby Fix

.github/pull_request_template.md, src/routes/LobbyRouter.ts, src/routes/QuoteRouter.ts
*Toegevoegd*: Je kan nu een user limit op je lobby zetten, dit kan als volgt:
Bij het aanmaken van de lobby `ei lobby create -5`
Later de lobby limit veranderen `ei lobby limit 2`
*Fixed*: De pret is over... Je kan geen \@everyone en \@here meer in quotes zetten
=> Ontvang thuis, op het balkon en in de tuin maximaal 6 gasten

src/routes/QuoteRouter.ts
**Changelog**:
```md
*Toegevoegd:* `ei quote user` is niet meer random, je kan nu één (1) selectie maken uit één (1) menu van quotes
```
=> Welk Kwootje Staat Er Op Het Menu?

src/createMenu.ts, src/entity/GuildUser.ts, src/entity/Quote.ts, src/migrations/Migration20200923103947.ts, src/routes/QuoteRouter.ts
**Changelog**:
```md
*Toegevoegd*: Je kan nu quotes verwijderen met `ei quote remove @<user>
Je kan quotes die jij hebt gemaakt verwijderen en je kan de quotes verwijderen van jezelf.
> Voor deze update werd er niet bijgehouden wie welke quote geschreven had, maar deze informatie is wel nodig om een quote te kunnen verwijderen. Om dit probleem op te lossen wordt elke quote op jou naam van jou.
```
=> Quotes Verwijderen

src/index.ts, src/routes/QuoteRouter.ts
**Changelog**:
```md
*Veranderd:* Admins kunnen nu quotes van iedereen verwijderen
*Toegevoegd*: Quote Help Menu
```
=> Admin Abuse Geïntroduceerd

src/EiNoah.ts, src/Router.ts, src/data.ts, src/entity/GuildUser.ts, src/entity/Quote.ts, src/index.ts, src/routes/Counter.ts, src/routes/LobbyRouter.ts, src/routes/QuoteRouter.ts, tsconfig.json
**Changelog**:
```md
*Veranderd:* Default lobby type veranderd naar mute `🔇`
*Veranderd:* Aantal commandos hebben Nederlandse aliases gekregen
*Fixed:* Mensen konden nogsteeds *@*everyone en *@*here toevoegen aan quotes
*Toegevoegd:* Sommige commando's kunnen nu DMed worden
*Fixed:* `ei quote` gaf een error bij het quoten van een ander persoon
*Fixed:* `ei quote` liet quotes zien van alle servers waar ei Noah in zat
> Er is verandering geweest aan de internals van ei Noah, het zou goed kunnen dat sommige dingen niet meer werken zoals verwacht
```
[Bij het squashen en mergen van …
=> Als Je Nou Een Klein Beetje Stricter Bent

src/routes/LobbyRouter.ts
**Changelog**:
```md
*Toegevoegd*: `ei lobby remove` geeft nu een menu weer met alle users en roles die verwijderd kunnen worden
*Fixed:* `ei lobby remove` gaf een error wanneer er geen argumenten gegeven waren
```
=> Alles Krijgt Een Menu

package-lock.json, package.json, src/Router.ts, src/entity/CoronaData.ts, src/entity/User.ts, src/entity/UserCoronaRegions.ts, src/index.ts, src/migrations/Migration20201007193137.ts, src/mikro-orm.config.ts, src/routes/CoronaRouter.ts, src/routes/LobbyRouter.ts, src/routes/QuoteRouter.ts
**Changelog**:
```md
*Toegevoegd:* Krijg een dagelijkse rapportage over de corona cijfers in jou regio
> Om bijvoorbeeld elke dag een rapportage te krijgen over de regio Zwolle typ `ei corona add Zwolle`, voor meer informatie typ `ei corona`
> Op dit moment moet je zelf uitreken hoeveel gevallen er per inwoners zijn, dit wordt later automatisch gedaan
*Fixed:* `ei quote <user> <quote>` geeft nu een error wanneer een quote meer dan 256 karakters bevat
```
=> Corona Cijfers Deze Week

.github/workflows/docker-publish.yml, package-lock.json, package.json, src/routes/CoronaRouter.ts
**Changelog**:
```md
*Toegevoegd*: Hoeveelheid per 100,000 inwoners wordt nu laten zien in het rapport
```
=> HOEVEEL PER 100,000????

docs/setup.md, package-lock.json, src/index.ts, src/migrations/Migration20210121211041.ts, src/routes/Birthday.ts, src/routes/CoronaRouter.ts, src/routes/LobbyRouter.ts, src/routes/QuoteRouter.ts
*Maybe*: 
**Changelog**:
```md
*Toegevoegd:* Laat iedereens leeftijd zien met `show-age`
*Toegevoegd:* Vraag iemands geboortedatum/ verjaardag op met `ei bday <@user>`
*Fixed:* Je kan niet meer je geboortedatum in de toekomst zetten (of in de middeleeuwen)
> Voeg opnieuw je verjaardag toe, als dit het geval is
*Veranderd:* Verjaardag announcement mooier gemaakt
*Toegevoegd:* Globaal help menu (`ei help`)
*Veranderd:* Manier waarop geboortedatum worden gesorteerd
```
=> Hoe Oud Ben Jij?

src/entity/GuildUser.ts, src/migrations/Migration20210201200058.ts, src/routes/LobbyRouter.ts
**Changelog**:
```md
*Toegevoegd*: Verander je lobby naam met `ei lobby name <nieuwe naam>`
```
=> Wat Zijn Zij Aan Het Doen?

package-lock.json, package.json, src/routes/LobbyRouter.ts
Emoji's kunnen blijkbaar meer dan 1 karakter lang zijn D:
Is het de eerste karakter of het eerste karakter???
**Changelog**:
```md
*Veranderd*: Geef **public** lobbies een custom icon door het eerste karakter een emoji te maken
> Op dit moment werkt dit alleen nog voor public lobbies om het lobby type duidelijk te maken
```
=> Wat Zijn Ze Aan Het Doen? 2.0

src/routes/LobbyRouter.ts
**Changelog**:
```md
*Fixed:* Lobby naam kon niet veranderd worden
```
=> Lobby Name Fix

src/routes/LobbyRouter.ts
**Changelog**:
```md
*Fixed*: Naam van de tekst lobby werd niet veranderd bij het fixen van de voice channel
```
=> Even Gelijk Trekken

.eslintrc, src/EiNoah.ts, src/routes/Birthday.ts, src/routes/CoronaRouter.ts, src/routes/LobbyRouter.ts
Exception handling beter gemaakt
**Changelog**:
```md
*Veranderd*: Lobby wordt nu verwijderd als er alleen een bot in zit
*Fixed*: Error wanneer er geen toestemming was om te praten
*Fixed*:  Commands kijken nu beter welke permissions ze nodig hebben
```
=> Lonely Bot :(

src/index.ts
**Changelog**:
```md
*Toegevoegd:* Voeg nu tekst toe aan je bedreiging
> BODEM TEKST
```
=> Steek tekst

src/EiNoah.ts, src/Router.ts, src/routes/LobbyRouter.ts, src/routes/QuoteRouter.ts
Misschien kan dit beter verwoord worden
**Changelog**:
```md
*Toegevoegd:* Je kan nu een quote aanmaken door op iemands bericht `ei quote` te reageren
*Veranderd:* Je kan nu mensen toevoegen aan je prive-lobby
> Dit heeft als gevolgen dat de prive-tekstkanalen niet meer zo prive zijn
```
=> Snel Quote Dit

.github/pull_request_template.md, .github/workflows/docker-publish.yml, src/EiNoah.ts, src/Router.ts, src/index.ts
En gelijk even testen met het steek commando want waarom niet
**Changelog**:
```md
*Toegevoegd*: Verander de bodemtekst van je knuffel of bedreiging door `-b <bodemtekst>` aan je message toe te voegen
```
=> Bodem Tekst

locales/en/translation.json, locales/nl/translation.json, package-lock.json, package.json, src/EiNoah.ts, src/child.ts, src/createMenu.ts, src/index.ts, src/router/ContextMenuInfo.ts, src/router/Router.ts, src/routes/Birthday.ts, src/routes/CoronaRouter.ts, src/routes/LobbyRouter.ts, src/routes/Locale.ts, src/routes/QuoteRouter.ts, src/routes/Simulator.ts
**Changelog**:
```md
*Toegevoegd:* Je kan nu de lobby naam aanpassen met een modal (pop-up)
*Verwijderd:* Ei-Noah commandos werken alleen nog maar met slash commands
*Veranderd:* Het dashboard van lobbies worden niet meer gepint
> Kreeg daar errors mee en heb niet kunnen uitvinden waarom
```
=> Nog Een Manier Om Je Lobby Te Hernoemen

.eslintrc, .vscode/launch.json, package-lock.json, package.json, src/EiNoah.ts, src/child.ts, src/createMenu.ts, src/index.ts, src/logger.ts, src/router/ContextMenuInfo.ts, src/router/LazyAutocompleteRouteInfo.ts, src/router/LazyMsgRouteInfo.ts, src/router/LazyRouteInfo.ts, src/router/Router.ts, src/routes/Birthday.ts, src/routes/CoronaRouter.ts, src/routes/Counter.ts, src/routes/LobbyRouter.ts, src/routes/Locale.ts, src/routes/QuoteRouter.ts, src/routes/Simulator.ts
**Changelog**:
```md
*trans people:* im trans
*society:* ok
*winston:* hi guys
*trans people:* holy shit its winston from overwatch
*winston:* overwatch
```
=> Winston from overwatch

apps/bot/package.json, apps/bot/src/routes/LobbyRouter.ts, apps/website/app/lobby/NameInput.tsx, packages/lobby/index.ts, pnpm-lock.yaml
**Changelog**:
```md
_Toegevoegd:_ Je kan nu je lobby super mooi maken met `ei lobby decorate`
_Fixed:_ Ei noah kwam werkelijk naar mensen hun huis om ze neer te steken, dit is nu gefixt
_Veranderd:_ Alle lobbies heten nu `Lobby` dit is om de identeit van de lobby owner te beschermen
```
=> Now sends date instead of number

apps/bot/auth.d.ts, apps/bot/src/routes/LobbyRouter.ts, packages/drizzle/tables/schema.ts, packages/lucia/app.d.ts, packages/trpc/auth.d.ts, packages/trpc/package.json, packages/trpc/src/routes/notification.ts, packages/trpc/src/trpc.ts, pnpm-lock.yaml
**Changelog**:
```md
_Toegevoegd:_ Je kan nu je lobby super mooi maken met `ei lobby decorate`
_Fixed:_ Ei noah kwam werkelijk naar mensen hun huis om ze neer te steken, dit is nu gefixt
_Veranderd:_ Alle lobbies heten nu `Lobby` dit is om de identeit van de lobby owner te beschermen
```
=> Session now holds push token
